// CH_INT.H

#ifndef _CH_INT_H
#define _CH_INT_H

#include "ch_define.h"

#define ENABLE_INT 0x0040
#define DISABLE_INT 0x0000

#define LEVEL_0 0x0000
#define LEVEL_1	0x0004
#define LEVEL_2	0x0008
#define LEVEL_3 0x000C
#define LEVEL_4 0x0010
#define LEVEL_5	0x0014
#define LEVEL_6	0x0018
#define LEVEL_7 0x001C
#define LEVEL_8 0x0020
#define LEVEL_9	0x0024
#define LEVEL_10 0x0028
#define LEVEL_11 0x002C
#define LEVEL_12 0x0030
#define LEVEL_13 0x0034
#define LEVEL_14 0x0038
#define LEVEL_15 0x003C

#define GROUP_0 0x0000
#define GROUP_1 0x0001
#define GROUP_2 0x0002
#define GROUP_3 0x0003
#define GROUP_4 0x0100
#define GROUP_5 0x0101
#define GROUP_6 0x0102
#define GROUP_7 0x0103

#define PFO_INT_ADR (0x02)
#define STACK_OVERFLOW_INT_ADR (0x04)
#define STACK_UNDERFLOW_INT_ADR (0x06)
#define CLASS_B_TRAP_INT_ADR (0x0A)

#define PLL_OWD_INT_ADR (0x43)
#define PLL_OWD_INT_LEVEL (LEVEL_14|GROUP_1)
#define PLL_OWD_INT_RB LEVEL_14_RB

// CC2_T8 (interrupt used to check clock and to generated 25ms in test mode every 1ms)
#define TIMER_INT_ADR (0x3D)
#define TIMER_CHECK_EVENT_LEVEL (LEVEL_10|GROUP_0)
#define TIMER_INT_RB LEVEL_10_RB

// CC2_CC20 (interrupt used for clock every second)
#define IIC_RTC_CLOCKOUT_INT_ADR (0x34)
#define IIC_RTC_CLOCKOUT_INT_LEVEL (LEVEL_9|GROUP_1)
#define IIC_RTC_CLOCKOUT_INT_RB LEVEL_9_RB

// ASC0_RIC
#define ASC0_RECEIVE_INT_ADR (0x2B)
#define ASC0_RECEIVE_INT_LEVEL (LEVEL_7|GROUP_1)
#define ASC0_RECEIVE_INT_RB LEVEL_7_RB

// ASC1_RIC
#define ASC1_RECEIVE_INT_ADR (0x49)
#define ASC1_RECEIVE_INT_LEVEL (LEVEL_7|GROUP_0)
#define ASC1_RECEIVE_INT_RB LEVEL_7_RB

// CAN
#define CAN_IO_ADR (0x55)
#define CAN_IO_EVENT_LEVEL (LEVEL_6|GROUP_1)
#define CAN_IO_RB LEVEL_6_RB

// CAN
#define CAN_BACKBONE_ADR (0x54)
#define CAN_BACKBONE_EVENT_LEVEL (LEVEL_6|GROUP_0)
#define CAN_BACKBONE_RB LEVEL_6_RB

// ASC0_EIC
#define ASC0_ERROR_INT_ADR (0x2C)
#define ASC0_ERROR_INT_LEVEL (LEVEL_5|GROUP_4)
#define ASC0_ERROR_INT_RB LEVEL_5_RB

// ASC1_EIC
#define ASC1_ERROR_INT_ADR (0x4A)
#define ASC1_ERROR_INT_LEVEL (LEVEL_5|GROUP_3)
#define ASC1_ERROR_INT_RB LEVEL_5_RB

// CC1_CC5
#define ASC1_DCD_INT_ADR (0x15)
#define ASC1_DCD_INT_LEVEL (LEVEL_5|GROUP_2)
#define ASC1_DCD_INT_RB LEVEL_5_RB

// ASC0_TBIC
#define ASC0_TRANSMITBUFFER_INT_ADR (0x47)
#define ASC0_TRANSMITBUFFER_INT_LEVEL (LEVEL_5|GROUP_1)
#define ASC0_TRANSMITBUFFER_INT_RB LEVEL_5_RB

// ASC1_TBIC
#define ASC1_TRANSMITBUFFER_INT_ADR (0x5E)
#define ASC1_TRANSMITBUFFER_INT_LEVEL (LEVEL_5|GROUP_0)
#define ASC1_TRANSMITBUFFER_INT_RB LEVEL_5_RB

// CC2_CC21 (JP 25-01-08)
#define CP2200_INT_ADR (0x35)
#define CP2200_INT_LEVEL (LEVEL_4|GROUP_0)
#define CP2200_INT_RB LEVEL_4_RB

// IIC_DTIC
#define IIC_DATA_EVENT_INT_ADR (0x40)
#define IIC_DATA_EVENT_INT_LEVEL (LEVEL_2|GROUP_1)
#define IIC_DATA_EVENT_INT_RB LEVEL_2_RB

// IIC_PEIC
#define IIC_PROTOCOL_EVENT_INT_ADR (0x41)
#define IIC_PROTOCOL_EVENT_INT_LEVEL (LEVEL_2|GROUP_0)
#define IIC_PROTOCOL_EVENT_INT_RB LEVEL_2_RB

// CC2_T8
#define KEY_INT_ADR (0x3E)
#define KEY_CHECK_EVENT_LEVEL (LEVEL_1|GROUP_0)
#define KEY_INT_RB LEVEL_1_RB

#endif // _CH_INT_H

