/*
 * co_init.c - generated  initialization file for a CANopen device
 *
 * Copyright 1998-2004 by port GmbH Halle(Saale) / Germany
 *-----------------------------------------------------------------------------
 *
 *-----------------------------------------------------------------------------
 *
 *
 * modification history
 * --------------------
 * $Log$
 * Revision 1.0  2011-07-18 11:49:03+02  driet
 * Initial revision
 *
 * Revision 1.2  2008-05-30 12:59:54+02  driet
 * <>
 *
 * 
 *-----------------------------------------------------------------------------
 */ 

 
/**
*  \file  co_init.c
*  initilization routine for the CANopen library
*  \author port GmbH, Halle (Saale)
*  $Revision$
*  $Date$
*
* This file contains the initialization functions for the CANopen library.
* It provides the function init_Library to initialize the library.
*
* It was generated by the CANopen Design Tool V 2.1.13 by port GmbH, Halle.
* Generation: 04-11-2008 09:57 AM
*
*/
/* header of standard C libraries */ 
#include <stdio.h>
#include <stdlib.h>

/* header of the CANopen Library */
#include <cal_conf.h>
#include <co_type.h>
#include <co_acces.h>
#include <co_nmt.h>
#include <co_lme.h>
#include <co_drv.h>
#include <co_sdo.h>
#include <co_pdo.h>
#include <co_emcy.h>
#include <co_sync.h>
#include <co_nmt_m.h>
/* Redefine the following expressions with your specific
 output functions.*/
#ifndef PRINTF
# define PRINTF(s, e)  
#endif
#ifndef PUTCHAR
# define PUTCHAR(e)    
#endif

/* Redefine INIT_USER_SETTINGS with your specific function. */
#ifndef INIT_USER_SETTINGS
# define INIT_USER_SETTINGS() 
#endif


#ifdef NO_PRINTF_S
# define PRINTRET(s) do {						\
		    if ( commonRet == CO_OK ) { PUTCHAR('0'); }		\
		    else { PUTCHAR('1'); return(commonRet); }		\
		  } while(0)
#else 
# define PRINTRET(s) do {						\
		    PRINTF( s": %d\n", (int) commonRet);         	\
		    if( commonRet != CO_OK ) return(commonRet);		\
		  } while(0)
#endif
 
/* Definition of init_Library */ 
/********************************************************************/
/**
*++\brief init_Library - initialization routine for the CANopen library
*--\brief init_Library - Initialisierungsroutine für die CANopen Bibliothek
*
*++ This function initializes the CANopen library
*++ and defines the CANopen services.
*-- Diese Funktion initialisiert die Bibliothek
*-- und definiert die CANopen-Dienste.
*
*\retval
*++ CO_OK in case of success
*++ or specific library error code of the failed function.
*-- CO_OK bei Erfolg
*-- oder spezifischer Rückgabewerte der fehlgeschlagenen Funktion.
*
*/
RET_T init_Library(void) { 
   RET_T 	commonRet;      /* return value for CANopen functions */ 
   UNSIGNED16	pdoNum =0;      /* pdo loop variable */ 


   /*--- inititializing of CANopen -----------------------------------*/ 
   /* defines also the Network control Object -- NMT 
    * reset communication and goes to the 
    * state preoperational + Initialization of CANopen */ 
    commonRet = initCANopen();
    PRINTRET("CANopen initialization");

   /* Call user defined function */

    INIT_USER_SETTINGS();

    /* Definition of CANopen Objects */
    /* ============================= */
    commonRet = defineSync(CONSUMER);
    PRINTRET("Line 0: Define Sync Consumer");

    /* definition of SDOs Line 0 
     * 1st parameter: SDO number 
     * 2nd parameter: SDO type: CLIENT  SERVER
     */
    commonRet = defineSdo (1, SERVER );
    PRINTRET("Line 0: Define 1st Server-SDO");

    /* definition of PDOs 
     * 1st parameter: type of PDO: RECEIVE | TRANSMIT
     * 2nd parameter: PDO number
     * 3rd parameter: permission for dynamically mapping
     */
    for (pdoNum = 1; pdoNum <= 9; pdoNum++) {
        commonRet = definePdo (RECEIVE_PDO, pdoNum, CO_TRUE );
        PRINTRET("Line 0: Define RECEIVE_PDO");
    }
    for (pdoNum = 1; pdoNum <= 11; pdoNum++) {
        commonRet = definePdo (TRANSMIT_PDO, pdoNum, CO_TRUE );
        PRINTRET("Line 0: Define TRANSMIT_PDO");
    }

   /* definition of EMCY Producer Line 0
    * 1st parameter: type of EMCY: PRODUCER | CONSUMER
    * 2nd parameter: EMCY number (unused for producers)
    * 3rd parameter: COB-ID (unused for producers)
    */
    commonRet = defineEmcy( PRODUCER, 0, 0 );
    PRINTRET("Line 0: Define Emcy-Producer");

    /* definition of the local node */
                     /* Nodeguarding, Heartbeat */
    commonRet = createNodeReq(CO_FALSE,CO_TRUE, CO_FALSE);
    PRINTRET("NMT Node created");

    /* Creating of the network (NMT-MASTER function)*/
    commonRet = createNetworkReq(CO_FALSE, CO_TRUE);
    PRINTRET("createNetworkReq");
    return(commonRet);
}

/* Definition of deinit_Library */ 
/********************************************************************/
/**
*++\brief deinit_Library - deinitialization routine for the CANopen library
*--\brief deinit_Library - Deinitialisierungsroutine für die CANopen Bibliothek
*
*++ This function deinitializes the CANopen library.
*-- Diese Funktion deinitialisiert die Bibliothek
*
*\retval
*++ CO_OK
*-- CO_OK
*
*/
RET_T deinit_Library(void) { 

    /* delete node object */
    deleteNodeReq();
    /* delete network object */
    deleteNetworkReq();

    /* leaves CAL/CANopen    */
    leaveCANopen();
    return(CO_OK);
}
