// CH_ALARM.H

#ifndef _CH_ALARM_H
#define _CH_ALARM_H

#include "ct_data.h"

#define ALARM_DISP_BLOCKED 60

#define GEEN_AL      0
#define ORION_OFF_AL 1	  
#define COMPUTER_AL  2
#define CAN_AL       3

// Emergencies CANopen
#define EMCY_NO_ERROR                         0x0000
#define EMCY_MOTOR_EMERGENCYSWITCH            0x0100
#define EMCY_MOTOR_THERMAL_CLOSE              0x0200
#define EMCY_MOTOR_THERMAL_OPEN               0x0300
#define EMCY_MOTOR_BREAK_INPUT                0x0400
#define EMCY_MOTOR_SPEED_TO_LOW               0x0600
#define EMCY_MOTOR_ENCODER_FAILURE            0x0700
#define EMCY_MOTOR_NO_FEEDBACK                0x0800
#define EMCY_MOTOR_NOT_ENOUGH_PULSES          0x0900
#define EMCY_MOTOR_PULSES_TO_FAST             0x0A00
#define EMCY_MOTOR_NOT_INSTALLED              0x0B00
#define EMCY_MOTOR_INSTALL_MODE               0x0C00
#define EMCY_MOTOR_ERROR_DEVIATION_POSITION   0x0D00
#define EMCY_MOTOR_DIRECTIONS_NOT_DEFINED     0x0E00
#define EMCY_MOTOR_SLAVE_COMMUNICATION        0x0F00
#define EMCY_MOTOR_SPEED_NOT_EQUAL            0x1000
#define EMCY_MOTOR_MULTIPLE_MASTER            0x1100
#define EMCY_MOTOR_SLAVE_NOT_INIT             0x1200
#define EMCY_MOTOR_FREQUENCY_CONTROLLER       0x1300
#define EMCY_MOTOR_BOARD_COMMUNICATION        0x1400
#define EMCY_MOTOR_MANUAL                     0x1500
#define EMCY_MOTOR_NOT_SYNCHRONOUS            0x1600
#define EMCY_MOTOR_LIMITSWITCHES_NOT_EQUAL    0x1700
#define EMCY_MOTOR_LIMITSWITCH_NOT_REACHED    0x1800
#define EMCY_MOTOR_WRONG_DIRECTION            0x1900
#define EMCY_MOTOR_LINK_UNKNOWN               0x1A00
#define EMCY_MOTOR_NOT_RUNNING                0x1B00
#define EMCY_MOTOR_ENCODER_FAILURE_A          0x1C00
#define EMCY_MOTOR_ENCODER_FAILURE_B          0x1D00
#define EMCY_MOTOR_ENCODER_INTERFERENCE       0x1E00
#define EMCY_MOTOR_DUALSCREEN_NOT_POSSIBLE    0x1F00
#define EMCY_MOTOR_WARNING_DEVIATION_POSITION 0x2000
#define EMCY_MOTOR_LIMITSWITCH_SAFETY_SPEED   0x2100

#define EMCY_DEVICE_MANUAL                    0x2200
#define EMCY_DEVICE_COMMUNICATION             0x2300
#define EMCY_DEVICE_TARGET_NOT_REACHED        0x2400

#define EMCY_VENT_LOCKED_MOTOR                0x2500
#define EMCY_VENT_HALL_FAILURE				  0x2600
#define EMCY_VENT_THERMAL_MOTOR				  0x2700
#define EMCY_VENT_COMM_ERROR_MASTER_SLAVE	  0x2800
#define EMCY_VENT_THERMAL_POWER_MODULE		  0x2900
#define EMCY_VENT_COMM_ERROR_REMOTE_UNIT	  0x2A00
#define EMCY_VENT_PHASE_FAILURE				  0x2B00
#define EMCY_VENT_BRAKE                       0x2C00
#define EMCY_VENT_LOW_LINE_VOLTAGE            0x2D00
#define EMCY_VENT_LOW_DC_LINK_VOLTAGE         0x2E00
#define EMCY_VENT_HIGH_DC_LINK_VOLTAGE        0x2F00
#define EMCY_VENT_DRIVER_PROBLEM              0x3000
#define EMCY_VENT_ELECTRONIC_BOX_OVER_HEAT    0x3100
#define EMCY_VENT_EXCESSIVE_DC_LINK_CURRENT   0x3200
#define EMCY_MOTOR_POSITION_NOT_REACHED       0x3300
#define EMCY_DEVICE_LIMITSWITCH               0x3400
#define EMCY_DEVICE_EXTERN_ALARM              0x3500
#define EMCY_VENT_UNKNOWN					  0x3E00
#define EMCY_MOTOR_UNKNOWN                    0x3F00
#define EMCY_GROUP_MANUAL                     0x4000
#define EMCY_LOST_HEARTBEAT                   0x8000

// ALGEMENE ALARMEN
#define ALGEMEEN_AL 10

#define MOTORGROUP_MANUAL_AL                10

#define MOTOR_MANUAL_AL                     20
#define MOTOR_EMERGENCYSWITCH_AL            21
#define MOTOR_THERMAL_CLOSE_AL              22
#define MOTOR_THERMAL_OPEN_AL               23
#define MOTOR_BREAK_INPUT_AL                24
#define MOTOR_SPEED_TO_LOW_AL               26
#define MOTOR_ENCODER_FAILURE_AL            27
#define MOTOR_NO_FEEDBACK_AL                28
#define MOTOR_NOT_ENOUGH_PULSES_AL          29
#define MOTOR_PULSES_TO_FAST_AL             30
#define MOTOR_NOT_INSTALLED_AL              31
#define MOTOR_ENCODER_INTERFERENCE_AL       32
#define MOTOR_INSTALL_MODE_AL               33
#define MOTOR_ERROR_DEVIATION_POSITION_AL   34
#define MOTOR_WARNING_DEVIATION_POSITION_AL 35
#define MOTOR_LIMITSWITCH_SAFETY_SPEED_AL   36
#define MOTOR_DIRECTIONS_NOT_DEFINED_AL     37
#define MOTOR_DUALSCREEN_NOT_POSSIBLE_AL    38
#define MOTOR_COMMUNICATION_AL              39 // H1MC
#define MOTOR_LIMITSWITCHES_NOT_EQUAL_AL    40 // H1MC
#define MOTOR_SPEED_NOT_EQUAL_AL            41 // H1MC
#define MOTOR_MULTIPLE_MASTER_AL            42 // H1MC
#define MOTOR_SLAVE_NOT_INIT_AL             43 // H1MC
#define MOTOR_FREQUENCY_CONTROLLER_AL       44 // H2MC-F
#define MOTOR_NOT_SYNCHRONOUS_AL            45 // H1MC
#define MOTOR_LIMITSWITCH_NOT_REACHED_AL    46 // H1MC
#define MOTOR_WRONG_DIRECTION_AL            47 // H1MC
#define MOTOR_EMERGENCY_POWER_AL            48 // EKU
#define MOTOR_LINK_UNKNOWN_AL               49
#define MOTOR_NOT_RUNNING_AL                50
#define MOTOR_ENCODER_FAILURE_A_AL          51
#define MOTOR_ENCODER_FAILURE_B_AL          52
#define MOTOR_POSITION_NOT_REACHED_AL       53
#define MOTOR_UNKNOWN_AL                    79

#define VENT_MANUAL_AL              80
#define VENT_TARGET_NOT_REACHED_AL  81

#define KLEP_MANUAL_AL              90
#define KLEP_TARGET_NOT_REACHED_AL  91
#define KLEP_LIMITSWITCH_AL         92
#define KLEP_EXTERN_ALARM_AL        93

#define LUCHTMENGKASTGROEP_MANUAL_AL                    100

#define LUCHTMENGKAST_MANUAL_AL                         110
#define LUCHTMENGKAST_VORST_AL                          111
#define LUCHTMENGKAST_EXTERN_AL                         112
#define LUCHTMENGKAST_DRUKVERSCHIL_AL                   113
#define LUCHTMENGKAST_RECIRCKLEP_TARGET_NOT_REACHED_AL  114
#define LUCHTMENGKAST_BUITENKLEP_TARGET_NOT_REACHED_AL  115
#define LUCHTMENGKAST_BINNENKLEP_TARGET_NOT_REACHED_AL  116
#define LUCHTMENGKAST_BOVENKLEP_TARGET_NOT_REACHED_AL   117
#define LUCHTMENGKAST_INBLAASVENT_TARGET_NOT_REACHED_AL 118
#define LUCHTMENGKAST_AFBLAASVENT_TARGET_NOT_REACHED_AL 119
#define LUCHTMENGKAST_VERWARMING_TARGET_NOT_REACHED_AL  120

// geeft aan dat er geen minimum alarm gegeven wordt
#define ORION_ON_AL 199

#define SYSTEEM_AL_HARD      200
#define SYSTEEM_AL_OPT       200
#define SYSTEEM_AL_SETP      201
#define SYSTEEM_AL_VAL_HR    202
//#define SYSTEEM_AL_ADC_INT   203                         /* SIRIUS-CL */
//#define SYSTEEM_AL_DAC       204                         /* SIRIUS-CL */
#define SYSTEEM_AL_I2C0      205
#define SYSTEEM_AL_EEP       206
//#define SYSTEEM_AL_I2C1      207                         /* SIRIUS-CL */
#define SYSTEEM_AL_RTC       208
#define SYSTEEM_AL_TIMER_1ms 209
#define SYSTEEM_AL_HTRAP     210
//#define SYSTEEM_AL_RS232     211                         /* SIRIUS-CL */
#define SYSTEEM_AL_RESTORE_OPTION_SETPOINT_FAILED 212
#define SYSTEEM_AL_PLL       213
#define INSTALLATIE_AL       214
#define SYSTEEM_GEHEUGEN_256K_AL  216
#define SYSTEEM_EEPROM_256K_AL    217

#define SYSTEEM_AL_ZACHT               300
#define SYSTEEM_AL_NEW_OPTION_SETPOINT 300 /* SIRIUS-CL */
#define SYSTEEM_AL_NEW_OPTION          301 /* SIRIUS-CL */
#define SYSTEEM_AL_NEW_SETPOINT        302 /* SIRIUS-CL */
#define SYSTEEM_AL_ALARM_GERESET       303
#define SYSTEEM_AL_OPSTART             304
#define SYSTEEM_AL_EEP_TAAL            306
#define SYSTEEM_AL_GEEN_ALARM_CONTACT  307

#define IO_06_14_BOARD_AL    440
#define IO_06_14_ONBEKEND_AL 441

#define IO_12_06_BOARD_AL    460
#define IO_12_06_ONBEKEND_AL 461

#define IO_08_09_BOARD_AL    480
#define IO_08_09_ONBEKEND_AL 481

#define IO_EKU_BOARD_AL      540
#define IO_EKU_ONBEKEND_AL   541

#define IO_H2MC_BOARD_AL     560
#define IO_H2MC_ONBEKEND_AL  561

#define IO_H1MC_BOARD_AL     580
#define IO_H1MC_ONBEKEND_AL  581

#define IO_05_07_BOARD_AL       600
#define IO_05_07_ONBEKEND_AL    601
#define IO_05_07_ADC_AL         602
#define IO_05_07_EXTERNE_24V_AL 603
#define IO_05_07_ANA_IN_1_AL    604
#define IO_05_07_ANA_IN_2_AL    605
#define IO_05_07_ANA_IN_3_AL    606
#define IO_05_07_ANA_IN_4_AL    607
#define IO_05_07_ANA_IN_5_AL    608
#define IO_05_07_VERSIE_AL      609

#define IO_07_07_BOARD_AL       620
#define IO_07_07_ONBEKEND_AL    621
#define IO_07_07_ADC_AL         622
#define IO_07_07_EXTERNE_24V_AL 623
#define IO_07_07_ANA_IN_1_AL    624
#define IO_07_07_ANA_IN_2_AL    625
#define IO_07_07_ANA_IN_3_AL    626
#define IO_07_07_ANA_IN_4_AL    627
#define IO_07_07_VERSIE_AL      628

//#define WEERSTATION_CAN_AL            900
// master alarm is als slave master niet kan bereiken
// slave alarm is als master slave niet kan bereiken
#define CAN_PC_MASTER_AL              901
//#define CAN_PC_SLAVE_AL               902
//#define CAN_FWS_MASTER_AL             903
//#define CAN_FWS_SLAVE_AL              904
//#define CAN_OPT_MASTER_AL             905
//#define CAN_OPT_SLAVE_AL              906
//#define CAN_FAN_FLAP_MASTER_AL        907
//#define CAN_FAN_FLAP_1_SLAVE_AL       908
//#define CAN_FAN_FLAP_2_SLAVE_AL       910
//#define KETEL_WARMTE_CAN_MASTER_AL    913
//#define KETEL_WARMTE_CAN_SLAVE_AL     914
//#define MENGKLEP_WARMTE_CAN_MASTER_AL 915
//#define MENGKLEP_WARMTE_CAN_SLAVE_AL  916
//#define KETEL_MINTEMP_CAN_MASTER_AL   917
//#define KETEL_MINTEMP_CAN_SLAVE_AL    918
#define CAN_PC_1_MASTER_AL            919
//#define CAN_PC_1_SLAVE_AL             920
#define CAN_PC_2_MASTER_AL            921
//#define CAN_PC_2_SLAVE_AL             922
#define CAN_PC_3_MASTER_AL            923
//#define CAN_PC_3_SLAVE_AL             924

//================= Alarm codes ecVentilatoren ===================
#define MB_DEVICE_UNKNOWN_AL                    0
#define MB_DEVICE_COMMUNICATION_AL              1
#define MB_DEVICE_LOCKED_MOTOR_AL               2 // ebmBus
#define MB_DEVICE_HALL_FAILURE_AL               3 // ebmBus
#define MB_DEVICE_THERMAL_MOTOR_AL              4 // ebmBus
#define MB_DEVICE_COMM_ERROR_MASTER_SLAVE_AL    5 // ebmBus
#define MB_DEVICE_THERMAL_POWER_MODULE_AL       6 // ebmBus
#define MB_DEVICE_COMM_ERROR_REMOTE_UNIT_AL     7 // ebmBus
#define MB_DEVICE_PHASE_FAILURE_AL              8 // ebmBus
#define MB_DEVICE_BRAKE_AL                      9 // ebmBus
#define MB_DEVICE_LOW_LINE_VOLTAGE_AL          10 // ebmBus
#define MB_DEVICE_LOW_DC_LINK_VOLTAGE_AL       11 // ebmBus
#define MB_DEVICE_HIGH_DC_LINK_VOLTAGE_AL      12 // ebmBus
#define MB_DEVICE_DRIVER_PROBLEM_AL            13 // ebmBus
#define MB_DEVICE_ELECTRONIC_BOX_OVER_HEAT_AL  14 // ebmBus
#define MB_DEVICE_EXCESSIVE_DC_LINK_CURRENT_AL 15 // ebmBus
#define MB_DEVICE_GENERAL_ERROR_AL             16 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_MOTOR_FAULT_AL               17 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_MOTOR_BLOCKED_AL             18 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_HEAT_SINK_TEMPERATURE_AL     19 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_GROUND_FAULT_AL              20 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_HALL_IC_FAULT_AL             21 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_OVERCURRENT_AL               22 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_LINE_FAULT_AL                23 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_LINE_INT_HEAT_SINK_SENSOR_AL 24 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_DC_RES_VOLTAGE_TO_HIGH_AL    25 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_WRONG_DIRECTION_AL           26 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_TEMPERATURE_LOWERING_AL      27 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_WRONG_CONNECTION_AL          28 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_EXTERNAL_FAULT_AL            29 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_FACTORY_SETTINGS_AL          30 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_EEP_ERROR_AL                 31 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_RTC_GENERAL_FAULT_AL         32 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_RTC_VOLTAGE_FAULT_AL         33 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_FILTER_CONTAMINATION_AL      34 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_TRANSFER_ERROR_AL            35 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_DATA_CONNECTION_LINE_AL      36 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_DATA_CONNECTION_CHECKSUM_AL  37 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_SENSOR_FAULT_INPUT_1_AL      38 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_SENSOR_FAULT_INPUT_2_AL      39 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_SENSOR_FAULT_INPUT_3_AL      40 // ZiehlAbegg ECblue Premium
#define MB_DEVICE_HIGH_LINE_VOLTAGE_AL         41 // ebmBus modbus
#define MB_DEVICE_I_LIMIT_AL                   42 // ebmBus modbus
#define MB_DEVICE_P_LIMIT_AL                   43 // ebmBus modbus
#define MB_DEVICE_TE_HIGH_AL                   44 // ebmBus modbus
#define MB_DEVICE_TM_HIGH_AL                   45 // ebmBus modbus
#define MB_DEVICE_TEI_HIGH_AL                  46 // ebmBus modbus
#define MB_DEVICE_UZ_LOW_AL                    47 // ebmBus modbus
#define MB_DEVICE_N_LOW_AL                     48 // ebmBus modbus
#define MB_DEVICE_IGBT_FAULT_AL                49 // ZiehlAbegg ECblue Modbus
#define MB_DEVICE_UZK_HI_AL                    50 // ZiehlAbegg ECblue Modbus
#define MB_DEVICE_UZK_LO_AL                    51 // ZiehlAbegg ECblue Modbus
#define MB_DEVICE_UIN_HI_AL                    52 // ZiehlAbegg ECblue Modbus
#define MB_DEVICE_UIN_LO_AL                    53 // ZiehlAbegg ECblue Modbus
#define MB_DEVICE_FAILURE_POWER_SECTION_AL     54 // Rosenberg
#define MB_DEVICE_UMAX_AL                      55 // Rosenberg
#define MB_DEVICE_UMIN_AL                      56 // Rosenberg
#define MB_DEVICE_OVERSPEED_AL                 57 // Rosenberg
#define MB_DEVICE_LOCKED_ROTOR_AL              58 // Rosenberg
#define MB_DEVICE_FAILURE                      59 // Climafan
#define MB_DEVICE_UNDERSPEED_AL                60 // Rosenberg gen 3
#define MB_DEVICE_24V_SUPPLY_OVERLOADED_AL     61 // Rosenberg gen 3
#define MB_DEVICE_INPUT_PHASE_ERROR_AL         62 // Rosenberg gen 3
#define MB_DEVICE_MOTOR_PHASE_ERROR_AL         63 // Rosenberg gen 3
#define MB_DEVICE_MEMORY_ERROR_AL              64 // Nicotra Gebhardt
#define MB_DEVICE_SHORT_CIRCUIT_AL             65 // Nicotra Gebhardt
#define MB_DEVICE_LOSS_OF_SYNCHRONISM_AL       66 // Nicotra Gebhardt
#define MB_DEVICE_INPUT_VOLTAGE_ERROR_AL       67 // Nicotra Gebhardt
#define MB_DEVICE_INPUT_RELAY_NOT_CLOSED_AL    68 // Nicotra Gebhardt
#define MB_DEVICE_HIGH_STARTING_CURRENT_AL     69 // Nicotra Gebhardt

#define VENT_MB_AL                           1000
#define VENT_MB_UNKNOWN_AL                   (VENT_MB_AL + MB_DEVICE_UNKNOWN_AL                  ) // 1000
#define VENT_MB_COMMUNICATION_AL             (VENT_MB_AL + MB_DEVICE_COMMUNICATION_AL            ) // 1001
#define VENT_MB_LOCKED_MOTOR_AL              (VENT_MB_AL + MB_DEVICE_LOCKED_MOTOR_AL             ) // 1002
#define VENT_MB_HALL_FAILURE_AL              (VENT_MB_AL + MB_DEVICE_HALL_FAILURE_AL             ) // 1003
#define VENT_MB_THERMAL_MOTOR_AL             (VENT_MB_AL + MB_DEVICE_THERMAL_MOTOR_AL            ) // 1004
#define VENT_MB_COMM_ERROR_MASTER_SLAVE_AL   (VENT_MB_AL + MB_DEVICE_COMM_ERROR_MASTER_SLAVE_AL  ) // 1005
#define VENT_MB_THERMAL_POWER_MODULE_AL      (VENT_MB_AL + MB_DEVICE_THERMAL_POWER_MODULE_AL     ) // 1006
#define VENT_MB_COMM_ERROR_REMOTE_UNIT_AL    (VENT_MB_AL + MB_DEVICE_COMM_ERROR_REMOTE_UNIT_AL   ) // 1007
#define VENT_MB_PHASE_FAILURE_AL             (VENT_MB_AL + MB_DEVICE_PHASE_FAILURE_AL            ) // 1008
#define VENT_MB_BRAKE_AL                     (VENT_MB_AL + MB_DEVICE_BRAKE_AL                    ) // 1009
#define VENT_MB_LOW_LINE_VOLTAGE_AL          (VENT_MB_AL + MB_DEVICE_LOW_LINE_VOLTAGE_AL         ) // 1010
#define VENT_MB_LOW_DC_LINK_VOLTAGE_AL       (VENT_MB_AL + MB_DEVICE_LOW_DC_LINK_VOLTAGE_AL      ) // 1011
#define VENT_MB_HIGH_DC_LINK_VOLTAGE_AL      (VENT_MB_AL + MB_DEVICE_HIGH_DC_LINK_VOLTAGE_AL     ) // 1012
#define VENT_MB_DRIVER_PROBLEM_AL            (VENT_MB_AL + MB_DEVICE_DRIVER_PROBLEM_AL           ) // 1013
#define VENT_MB_ELECTRONIC_BOX_OVER_HEAT_AL  (VENT_MB_AL + MB_DEVICE_ELECTRONIC_BOX_OVER_HEAT_AL ) // 1014
#define VENT_MB_EXCESSIVE_DC_LINK_CURRENT_AL (VENT_MB_AL + MB_DEVICE_EXCESSIVE_DC_LINK_CURRENT_AL) // 1015
#define VENT_MB_GENERAL_ERROR_AL             (VENT_MB_AL + MB_DEVICE_GENERAL_ERROR_AL            ) // 1016
#define VENT_MB_MOTOR_FAULT_AL               (VENT_MB_AL + MB_DEVICE_MOTOR_FAULT_AL              ) // 1017
#define VENT_MB_MOTOR_BLOCKED_AL             (VENT_MB_AL + MB_DEVICE_MOTOR_BLOCKED_AL            ) // 1018
#define VENT_MB_HEAT_SINK_TEMPERATURE_AL     (VENT_MB_AL + MB_DEVICE_HEAT_SINK_TEMPERATURE_AL    ) // 1019
#define VENT_MB_GROUND_FAULT_AL              (VENT_MB_AL + MB_DEVICE_GROUND_FAULT_AL             ) // 1020
#define VENT_MB_HALL_IC_FAULT_AL             (VENT_MB_AL + MB_DEVICE_HALL_IC_FAULT_AL            ) // 1021
#define VENT_MB_OVERCURRENT_AL               (VENT_MB_AL + MB_DEVICE_OVERCURRENT_AL              ) // 1022
#define VENT_MB_LINE_FAULT_AL                (VENT_MB_AL + MB_DEVICE_LINE_FAULT_AL               ) // 1023
#define VENT_MB_LINE_INT_HEAT_SINK_SENSOR_AL (VENT_MB_AL + MB_DEVICE_LINE_INT_HEAT_SINK_SENSOR_AL) // 1024
#define VENT_MB_DC_RES_VOLTAGE_TO_HIGH_AL    (VENT_MB_AL + MB_DEVICE_DC_RES_VOLTAGE_TO_HIGH_AL   ) // 1025
#define VENT_MB_WRONG_DIRECTION_AL           (VENT_MB_AL + MB_DEVICE_WRONG_DIRECTION_AL          ) // 1026
#define VENT_MB_TEMPERATURE_LOWERING_AL      (VENT_MB_AL + MB_DEVICE_TEMPERATURE_LOWERING_AL     ) // 1027
#define VENT_MB_WRONG_CONNECTION_AL          (VENT_MB_AL + MB_DEVICE_WRONG_CONNECTION_AL         ) // 1028
#define VENT_MB_EXTERNAL_FAULT_AL            (VENT_MB_AL + MB_DEVICE_EXTERNAL_FAULT_AL           ) // 1029
#define VENT_MB_FACTORY_SETTINGS_AL          (VENT_MB_AL + MB_DEVICE_FACTORY_SETTINGS_AL         ) // 1030
#define VENT_MB_EEP_ERROR_AL                 (VENT_MB_AL + MB_DEVICE_EEP_ERROR_AL                ) // 1031
#define VENT_MB_RTC_GENERAL_FAULT_AL         (VENT_MB_AL + MB_DEVICE_RTC_GENERAL_FAULT_AL        ) // 1032
#define VENT_MB_RTC_VOLTAGE_FAULT_AL         (VENT_MB_AL + MB_DEVICE_RTC_VOLTAGE_FAULT_AL        ) // 1033
#define VENT_MB_FILTER_CONTAMINATION_AL      (VENT_MB_AL + MB_DEVICE_FILTER_CONTAMINATION_AL     ) // 1034
#define VENT_MB_TRANSFER_ERROR_AL            (VENT_MB_AL + MB_DEVICE_TRANSFER_ERROR_AL           ) // 1035
#define VENT_MB_DATA_CONNECTION_LINE_AL      (VENT_MB_AL + MB_DEVICE_DATA_CONNECTION_LINE_AL     ) // 1036
#define VENT_MB_DATA_CONNECTION_CHECKSUM_AL  (VENT_MB_AL + MB_DEVICE_DATA_CONNECTION_CHECKSUM_AL ) // 1037
#define VENT_MB_SENSOR_FAULT_INPUT_1_AL      (VENT_MB_AL + MB_DEVICE_SENSOR_FAULT_INPUT_1_AL     ) // 1038
#define VENT_MB_SENSOR_FAULT_INPUT_2_AL      (VENT_MB_AL + MB_DEVICE_SENSOR_FAULT_INPUT_2_AL     ) // 1039
#define VENT_MB_SENSOR_FAULT_INPUT_3_AL      (VENT_MB_AL + MB_DEVICE_SENSOR_FAULT_INPUT_3_AL     ) // 1040
#define VENT_MB_HIGH_LINE_VOLTAGE_AL         (VENT_MB_AL + MB_DEVICE_HIGH_LINE_VOLTAGE_AL        ) // 1041
#define VENT_MB_I_LIMIT_AL                   (VENT_MB_AL + MB_DEVICE_I_LIMIT_AL                  ) // 1042
#define VENT_MB_P_LIMIT_AL                   (VENT_MB_AL + MB_DEVICE_P_LIMIT_AL                  ) // 1043
#define VENT_MB_TE_HIGH_AL                   (VENT_MB_AL + MB_DEVICE_TE_HIGH_AL                  ) // 1044
#define VENT_MB_TM_HIGH_AL                   (VENT_MB_AL + MB_DEVICE_TM_HIGH_AL                  ) // 1045
#define VENT_MB_TEI_HIGH_AL                  (VENT_MB_AL + MB_DEVICE_TEI_HIGH_AL                 ) // 1046
#define VENT_MB_UZ_LOW_AL                    (VENT_MB_AL + MB_DEVICE_UZ_LOW_AL                   ) // 1047
#define VENT_MB_N_LOW_AL                     (VENT_MB_AL + MB_DEVICE_N_LOW_AL                    ) // 1048
#define VENT_MB_IGBT_FAULT_AL                (VENT_MB_AL + MB_DEVICE_IGBT_FAULT_AL               ) // 1049
#define VENT_MB_UZK_HI_AL                    (VENT_MB_AL + MB_DEVICE_UZK_HI_AL                   ) // 1050
#define VENT_MB_UZK_LO_AL                    (VENT_MB_AL + MB_DEVICE_UZK_LO_AL                   ) // 1051
#define VENT_MB_UIN_HI_AL                    (VENT_MB_AL + MB_DEVICE_UIN_HI_AL                   ) // 1052
#define VENT_MB_UIN_LO_AL                    (VENT_MB_AL + MB_DEVICE_UIN_LO_AL                   ) // 1053
#define VENT_MB_FAILURE_POWER_SECTION_AL     (VENT_MB_AL + MB_DEVICE_FAILURE_POWER_SECTION_AL    ) // 1054
#define VENT_MB_UMAX_AL                      (VENT_MB_AL + MB_DEVICE_UMAX_AL                     ) // 1055
#define VENT_MB_UMIN_AL                      (VENT_MB_AL + MB_DEVICE_UMIN_AL                     ) // 1056
#define VENT_MB_OVERSPEED_AL                 (VENT_MB_AL + MB_DEVICE_OVERSPEED_AL                ) // 1057
#define VENT_MB_LOCKED_ROTOR_AL              (VENT_MB_AL + MB_DEVICE_LOCKED_ROTOR_AL             ) // 1058
#define VENT_MB_UNDERSPEED_AL                (VENT_MB_AL + MB_DEVICE_UNDERSPEED_AL               ) // 1059
#define VENT_MB_24V_SUPPLY_OVERLOADED_AL     (VENT_MB_AL + MB_DEVICE_24V_SUPPLY_OVERLOADED_AL    ) // 1060
#define VENT_MB_INPUT_PHASE_ERROR_AL         (VENT_MB_AL + MB_DEVICE_INPUT_PHASE_ERROR_AL        ) // 1061
#define VENT_MB_MOTOR_PHASE_ERROR_AL         (VENT_MB_AL + MB_DEVICE_MOTOR_PHASE_ERROR_AL        ) // 1062
#define VENT_MB_MEMORY_ERROR_AL              (VENT_MB_AL + MB_DEVICE_MEMORY_ERROR_AL             ) // 1063
#define VENT_MB_SHORT_CIRCUIT_AL             (VENT_MB_AL + MB_DEVICE_SHORT_CIRCUIT_AL            ) // 1064
#define VENT_MB_LOSS_OF_SYNCHRONISM_AL       (VENT_MB_AL + MB_DEVICE_LOSS_OF_SYNCHRONISM_AL      ) // 1065
#define VENT_MB_INPUT_VOLTAGE_ERROR_AL       (VENT_MB_AL + MB_DEVICE_INPUT_VOLTAGE_ERROR_AL      ) // 1066
#define VENT_MB_INPUT_RELAY_NOT_CLOSED_AL    (VENT_MB_AL + MB_DEVICE_INPUT_RELAY_NOT_CLOSED_AL   ) // 1067
#define VENT_MB_HIGH_STARTING_CURRENT_AL     (VENT_MB_AL + MB_DEVICE_HIGH_STARTING_CURRENT_AL    ) // 1068
																								 
#define LUCHTMENGKAST_INBLAASVENT_MB_AL                           1100
#define LUCHTMENGKAST_INBLAASVENT_MB_UNKNOWN_AL                   (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_UNKNOWN_AL                  ) // 1100
#define LUCHTMENGKAST_INBLAASVENT_MB_COMMUNICATION_AL             (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_COMMUNICATION_AL            ) // 1101
#define LUCHTMENGKAST_INBLAASVENT_MB_LOCKED_MOTOR_AL              (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_LOCKED_MOTOR_AL             ) // 1102
#define LUCHTMENGKAST_INBLAASVENT_MB_HALL_FAILURE_AL              (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_HALL_FAILURE_AL             ) // 1103
#define LUCHTMENGKAST_INBLAASVENT_MB_THERMAL_MOTOR_AL             (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_THERMAL_MOTOR_AL            ) // 1104
#define LUCHTMENGKAST_INBLAASVENT_MB_COMM_ERROR_MASTER_SLAVE_AL   (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_COMM_ERROR_MASTER_SLAVE_AL  ) // 1105
#define LUCHTMENGKAST_INBLAASVENT_MB_THERMAL_POWER_MODULE_AL      (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_THERMAL_POWER_MODULE_AL     ) // 1106
#define LUCHTMENGKAST_INBLAASVENT_MB_COMM_ERROR_REMOTE_UNIT_AL    (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_COMM_ERROR_REMOTE_UNIT_AL   ) // 1107
#define LUCHTMENGKAST_INBLAASVENT_MB_PHASE_FAILURE_AL             (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_PHASE_FAILURE_AL            ) // 1108
#define LUCHTMENGKAST_INBLAASVENT_MB_BRAKE_AL                     (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_BRAKE_AL                    ) // 1109
#define LUCHTMENGKAST_INBLAASVENT_MB_LOW_LINE_VOLTAGE_AL          (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_LOW_LINE_VOLTAGE_AL         ) // 1110
#define LUCHTMENGKAST_INBLAASVENT_MB_LOW_DC_LINK_VOLTAGE_AL       (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_LOW_DC_LINK_VOLTAGE_AL      ) // 1111
#define LUCHTMENGKAST_INBLAASVENT_MB_HIGH_DC_LINK_VOLTAGE_AL      (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_HIGH_DC_LINK_VOLTAGE_AL     ) // 1112
#define LUCHTMENGKAST_INBLAASVENT_MB_DRIVER_PROBLEM_AL            (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_DRIVER_PROBLEM_AL           ) // 1113
#define LUCHTMENGKAST_INBLAASVENT_MB_ELECTRONIC_BOX_OVER_HEAT_AL  (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_ELECTRONIC_BOX_OVER_HEAT_AL ) // 1114
#define LUCHTMENGKAST_INBLAASVENT_MB_EXCESSIVE_DC_LINK_CURRENT_AL (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_EXCESSIVE_DC_LINK_CURRENT_AL) // 1115
#define LUCHTMENGKAST_INBLAASVENT_MB_GENERAL_ERROR_AL             (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_GENERAL_ERROR_AL            ) // 1116
#define LUCHTMENGKAST_INBLAASVENT_MB_MOTOR_FAULT_AL               (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_MOTOR_FAULT_AL              ) // 1117
#define LUCHTMENGKAST_INBLAASVENT_MB_MOTOR_BLOCKED_AL             (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_MOTOR_BLOCKED_AL            ) // 1118
#define LUCHTMENGKAST_INBLAASVENT_MB_HEAT_SINK_TEMPERATURE_AL     (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_HEAT_SINK_TEMPERATURE_AL    ) // 1119
#define LUCHTMENGKAST_INBLAASVENT_MB_GROUND_FAULT_AL              (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_GROUND_FAULT_AL             ) // 1120
#define LUCHTMENGKAST_INBLAASVENT_MB_HALL_IC_FAULT_AL             (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_HALL_IC_FAULT_AL            ) // 1121
#define LUCHTMENGKAST_INBLAASVENT_MB_OVERCURRENT_AL               (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_OVERCURRENT_AL              ) // 1122
#define LUCHTMENGKAST_INBLAASVENT_MB_LINE_FAULT_AL                (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_LINE_FAULT_AL               ) // 1123
#define LUCHTMENGKAST_INBLAASVENT_MB_LINE_INT_HEAT_SINK_SENSOR_AL (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_LINE_INT_HEAT_SINK_SENSOR_AL) // 1124
#define LUCHTMENGKAST_INBLAASVENT_MB_DC_RES_VOLTAGE_TO_HIGH_AL    (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_DC_RES_VOLTAGE_TO_HIGH_AL   ) // 1125
#define LUCHTMENGKAST_INBLAASVENT_MB_WRONG_DIRECTION_AL           (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_WRONG_DIRECTION_AL          ) // 1126
#define LUCHTMENGKAST_INBLAASVENT_MB_TEMPERATURE_LOWERING_AL      (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_TEMPERATURE_LOWERING_AL     ) // 1127
#define LUCHTMENGKAST_INBLAASVENT_MB_WRONG_CONNECTION_AL          (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_WRONG_CONNECTION_AL         ) // 1128
#define LUCHTMENGKAST_INBLAASVENT_MB_EXTERNAL_FAULT_AL            (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_EXTERNAL_FAULT_AL           ) // 1129
#define LUCHTMENGKAST_INBLAASVENT_MB_FACTORY_SETTINGS_AL          (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_FACTORY_SETTINGS_AL         ) // 1130
#define LUCHTMENGKAST_INBLAASVENT_MB_EEP_ERROR_AL                 (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_EEP_ERROR_AL                ) // 1131
#define LUCHTMENGKAST_INBLAASVENT_MB_RTC_GENERAL_FAULT_AL         (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_RTC_GENERAL_FAULT_AL        ) // 1132
#define LUCHTMENGKAST_INBLAASVENT_MB_RTC_VOLTAGE_FAULT_AL         (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_RTC_VOLTAGE_FAULT_AL        ) // 1133
#define LUCHTMENGKAST_INBLAASVENT_MB_FILTER_CONTAMINATION_AL      (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_FILTER_CONTAMINATION_AL     ) // 1134
#define LUCHTMENGKAST_INBLAASVENT_MB_TRANSFER_ERROR_AL            (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_TRANSFER_ERROR_AL           ) // 1135
#define LUCHTMENGKAST_INBLAASVENT_MB_DATA_CONNECTION_LINE_AL      (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_DATA_CONNECTION_LINE_AL     ) // 1136
#define LUCHTMENGKAST_INBLAASVENT_MB_DATA_CONNECTION_CHECKSUM_AL  (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_DATA_CONNECTION_CHECKSUM_AL ) // 1137
#define LUCHTMENGKAST_INBLAASVENT_MB_SENSOR_FAULT_INPUT_1_AL      (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_SENSOR_FAULT_INPUT_1_AL     ) // 1138
#define LUCHTMENGKAST_INBLAASVENT_MB_SENSOR_FAULT_INPUT_2_AL      (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_SENSOR_FAULT_INPUT_2_AL     ) // 1139
#define LUCHTMENGKAST_INBLAASVENT_MB_SENSOR_FAULT_INPUT_3_AL      (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_SENSOR_FAULT_INPUT_3_AL     ) // 1140
#define LUCHTMENGKAST_INBLAASVENT_MB_HIGH_LINE_VOLTAGE_AL         (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_HIGH_LINE_VOLTAGE_AL        ) // 1141
#define LUCHTMENGKAST_INBLAASVENT_MB_I_LIMIT_AL                   (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_I_LIMIT_AL                  ) // 1142
#define LUCHTMENGKAST_INBLAASVENT_MB_P_LIMIT_AL                   (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_P_LIMIT_AL                  ) // 1143
#define LUCHTMENGKAST_INBLAASVENT_MB_TE_HIGH_AL                   (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_TE_HIGH_AL                  ) // 1144
#define LUCHTMENGKAST_INBLAASVENT_MB_TM_HIGH_AL                   (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_TM_HIGH_AL                  ) // 1145
#define LUCHTMENGKAST_INBLAASVENT_MB_TEI_HIGH_AL                  (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_TEI_HIGH_AL                 ) // 1146
#define LUCHTMENGKAST_INBLAASVENT_MB_UZ_LOW_AL                    (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_UZ_LOW_AL                   ) // 1147
#define LUCHTMENGKAST_INBLAASVENT_MB_N_LOW_AL                     (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_N_LOW_AL                    ) // 1148
#define LUCHTMENGKAST_INBLAASVENT_MB_IGBT_FAULT_AL                (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_IGBT_FAULT_AL               ) // 1149
#define LUCHTMENGKAST_INBLAASVENT_MB_UZK_HI_AL                    (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_UZK_HI_AL                   ) // 1150
#define LUCHTMENGKAST_INBLAASVENT_MB_UZK_LO_AL                    (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_UZK_LO_AL                   ) // 1151
#define LUCHTMENGKAST_INBLAASVENT_MB_UIN_HI_AL                    (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_UIN_HI_AL                   ) // 1152
#define LUCHTMENGKAST_INBLAASVENT_MB_UIN_LO_AL                    (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_UIN_LO_AL                   ) // 1153
#define LUCHTMENGKAST_INBLAASVENT_MB_FAILURE_POWER_SECTION_AL     (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_FAILURE_POWER_SECTION_AL    ) // 1154
#define LUCHTMENGKAST_INBLAASVENT_MB_UMAX_AL                      (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_UMAX_AL                     ) // 1155
#define LUCHTMENGKAST_INBLAASVENT_MB_UMIN_AL                      (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_UMIN_AL                     ) // 1156
#define LUCHTMENGKAST_INBLAASVENT_MB_OVERSPEED_AL                 (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_OVERSPEED_AL                ) // 1157
#define LUCHTMENGKAST_INBLAASVENT_MB_LOCKED_ROTOR_AL              (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_LOCKED_ROTOR_AL             ) // 1158
#define LUCHTMENGKAST_INBLAASVENT_MB_UNDERSPEED_AL                (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_UNDERSPEED_AL               ) // 1159
#define LUCHTMENGKAST_INBLAASVENT_MB_24V_SUPPLY_OVERLOADED_AL     (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_24V_SUPPLY_OVERLOADED_AL    ) // 1160
#define LUCHTMENGKAST_INBLAASVENT_MB_INPUT_PHASE_ERROR_AL         (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_INPUT_PHASE_ERROR_AL        ) // 1061
#define LUCHTMENGKAST_INBLAASVENT_MB_MOTOR_PHASE_ERROR_AL         (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_MOTOR_PHASE_ERROR_AL        ) // 1062
#define LUCHTMENGKAST_INBLAASVENT_MB_MEMORY_ERROR_AL              (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_MEMORY_ERROR_AL             ) // 1063
#define LUCHTMENGKAST_INBLAASVENT_MB_SHORT_CIRCUIT_AL             (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_SHORT_CIRCUIT_AL            ) // 1064
#define LUCHTMENGKAST_INBLAASVENT_MB_LOSS_OF_SYNCHRONISM_AL       (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_LOSS_OF_SYNCHRONISM_AL      ) // 1065
#define LUCHTMENGKAST_INBLAASVENT_MB_INPUT_VOLTAGE_ERROR_AL       (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_INPUT_VOLTAGE_ERROR_AL      ) // 1066
#define LUCHTMENGKAST_INBLAASVENT_MB_INPUT_RELAY_NOT_CLOSED_AL    (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_INPUT_RELAY_NOT_CLOSED_AL   ) // 1067
#define LUCHTMENGKAST_INBLAASVENT_MB_HIGH_STARTING_CURRENT_AL     (LUCHTMENGKAST_INBLAASVENT_MB_AL + MB_DEVICE_HIGH_STARTING_CURRENT_AL    ) // 1068

#define LUCHTMENGKAST_AFBLAASVENT_MB_AL                           1200
#define LUCHTMENGKAST_AFBLAASVENT_MB_UNKNOWN_AL                   (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_UNKNOWN_AL                  ) // 1200
#define LUCHTMENGKAST_AFBLAASVENT_MB_COMMUNICATION_AL             (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_COMMUNICATION_AL            ) // 1201
#define LUCHTMENGKAST_AFBLAASVENT_MB_LOCKED_MOTOR_AL              (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_LOCKED_MOTOR_AL             ) // 1202
#define LUCHTMENGKAST_AFBLAASVENT_MB_HALL_FAILURE_AL              (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_HALL_FAILURE_AL             ) // 1203
#define LUCHTMENGKAST_AFBLAASVENT_MB_THERMAL_MOTOR_AL             (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_THERMAL_MOTOR_AL            ) // 1204
#define LUCHTMENGKAST_AFBLAASVENT_MB_COMM_ERROR_MASTER_SLAVE_AL   (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_COMM_ERROR_MASTER_SLAVE_AL  ) // 1205
#define LUCHTMENGKAST_AFBLAASVENT_MB_THERMAL_POWER_MODULE_AL      (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_THERMAL_POWER_MODULE_AL     ) // 1206
#define LUCHTMENGKAST_AFBLAASVENT_MB_COMM_ERROR_REMOTE_UNIT_AL    (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_COMM_ERROR_REMOTE_UNIT_AL   ) // 1207
#define LUCHTMENGKAST_AFBLAASVENT_MB_PHASE_FAILURE_AL             (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_PHASE_FAILURE_AL            ) // 1208
#define LUCHTMENGKAST_AFBLAASVENT_MB_BRAKE_AL                     (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_BRAKE_AL                    ) // 1209
#define LUCHTMENGKAST_AFBLAASVENT_MB_LOW_LINE_VOLTAGE_AL          (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_LOW_LINE_VOLTAGE_AL         ) // 1210
#define LUCHTMENGKAST_AFBLAASVENT_MB_LOW_DC_LINK_VOLTAGE_AL       (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_LOW_DC_LINK_VOLTAGE_AL      ) // 1211
#define LUCHTMENGKAST_AFBLAASVENT_MB_HIGH_DC_LINK_VOLTAGE_AL      (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_HIGH_DC_LINK_VOLTAGE_AL     ) // 1212
#define LUCHTMENGKAST_AFBLAASVENT_MB_DRIVER_PROBLEM_AL            (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_DRIVER_PROBLEM_AL           ) // 1213
#define LUCHTMENGKAST_AFBLAASVENT_MB_ELECTRONIC_BOX_OVER_HEAT_AL  (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_ELECTRONIC_BOX_OVER_HEAT_AL ) // 1214
#define LUCHTMENGKAST_AFBLAASVENT_MB_EXCESSIVE_DC_LINK_CURRENT_AL (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_EXCESSIVE_DC_LINK_CURRENT_AL) // 1215
#define LUCHTMENGKAST_AFBLAASVENT_MB_GENERAL_ERROR_AL             (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_GENERAL_ERROR_AL            ) // 1216
#define LUCHTMENGKAST_AFBLAASVENT_MB_MOTOR_FAULT_AL               (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_MOTOR_FAULT_AL              ) // 1217
#define LUCHTMENGKAST_AFBLAASVENT_MB_MOTOR_BLOCKED_AL             (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_MOTOR_BLOCKED_AL            ) // 1218
#define LUCHTMENGKAST_AFBLAASVENT_MB_HEAT_SINK_TEMPERATURE_AL     (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_HEAT_SINK_TEMPERATURE_AL    ) // 1219
#define LUCHTMENGKAST_AFBLAASVENT_MB_GROUND_FAULT_AL              (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_GROUND_FAULT_AL             ) // 1220
#define LUCHTMENGKAST_AFBLAASVENT_MB_HALL_IC_FAULT_AL             (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_HALL_IC_FAULT_AL            ) // 1221
#define LUCHTMENGKAST_AFBLAASVENT_MB_OVERCURRENT_AL               (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_OVERCURRENT_AL              ) // 1222
#define LUCHTMENGKAST_AFBLAASVENT_MB_LINE_FAULT_AL                (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_LINE_FAULT_AL               ) // 1223
#define LUCHTMENGKAST_AFBLAASVENT_MB_LINE_INT_HEAT_SINK_SENSOR_AL (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_LINE_INT_HEAT_SINK_SENSOR_AL) // 1224
#define LUCHTMENGKAST_AFBLAASVENT_MB_DC_RES_VOLTAGE_TO_HIGH_AL    (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_DC_RES_VOLTAGE_TO_HIGH_AL   ) // 1225
#define LUCHTMENGKAST_AFBLAASVENT_MB_WRONG_DIRECTION_AL           (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_WRONG_DIRECTION_AL          ) // 1226
#define LUCHTMENGKAST_AFBLAASVENT_MB_TEMPERATURE_LOWERING_AL      (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_TEMPERATURE_LOWERING_AL     ) // 1227
#define LUCHTMENGKAST_AFBLAASVENT_MB_WRONG_CONNECTION_AL          (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_WRONG_CONNECTION_AL         ) // 1228
#define LUCHTMENGKAST_AFBLAASVENT_MB_EXTERNAL_FAULT_AL            (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_EXTERNAL_FAULT_AL           ) // 1229
#define LUCHTMENGKAST_AFBLAASVENT_MB_FACTORY_SETTINGS_AL          (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_FACTORY_SETTINGS_AL         ) // 1230
#define LUCHTMENGKAST_AFBLAASVENT_MB_EEP_ERROR_AL                 (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_EEP_ERROR_AL                ) // 1231
#define LUCHTMENGKAST_AFBLAASVENT_MB_RTC_GENERAL_FAULT_AL         (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_RTC_GENERAL_FAULT_AL        ) // 1232
#define LUCHTMENGKAST_AFBLAASVENT_MB_RTC_VOLTAGE_FAULT_AL         (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_RTC_VOLTAGE_FAULT_AL        ) // 1233
#define LUCHTMENGKAST_AFBLAASVENT_MB_FILTER_CONTAMINATION_AL      (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_FILTER_CONTAMINATION_AL     ) // 1234
#define LUCHTMENGKAST_AFBLAASVENT_MB_TRANSFER_ERROR_AL            (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_TRANSFER_ERROR_AL           ) // 1235
#define LUCHTMENGKAST_AFBLAASVENT_MB_DATA_CONNECTION_LINE_AL      (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_DATA_CONNECTION_LINE_AL     ) // 1236
#define LUCHTMENGKAST_AFBLAASVENT_MB_DATA_CONNECTION_CHECKSUM_AL  (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_DATA_CONNECTION_CHECKSUM_AL ) // 1237
#define LUCHTMENGKAST_AFBLAASVENT_MB_SENSOR_FAULT_INPUT_1_AL      (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_SENSOR_FAULT_INPUT_1_AL     ) // 1238
#define LUCHTMENGKAST_AFBLAASVENT_MB_SENSOR_FAULT_INPUT_2_AL      (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_SENSOR_FAULT_INPUT_2_AL     ) // 1239
#define LUCHTMENGKAST_AFBLAASVENT_MB_SENSOR_FAULT_INPUT_3_AL      (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_SENSOR_FAULT_INPUT_3_AL     ) // 1240
#define LUCHTMENGKAST_AFBLAASVENT_MB_HIGH_LINE_VOLTAGE_AL         (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_HIGH_LINE_VOLTAGE_AL        ) // 1241
#define LUCHTMENGKAST_AFBLAASVENT_MB_I_LIMIT_AL                   (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_I_LIMIT_AL                  ) // 1242
#define LUCHTMENGKAST_AFBLAASVENT_MB_P_LIMIT_AL                   (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_P_LIMIT_AL                  ) // 1243
#define LUCHTMENGKAST_AFBLAASVENT_MB_TE_HIGH_AL                   (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_TE_HIGH_AL                  ) // 1244
#define LUCHTMENGKAST_AFBLAASVENT_MB_TM_HIGH_AL                   (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_TM_HIGH_AL                  ) // 1245
#define LUCHTMENGKAST_AFBLAASVENT_MB_TEI_HIGH_AL                  (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_TEI_HIGH_AL                 ) // 1246
#define LUCHTMENGKAST_AFBLAASVENT_MB_UZ_LOW_AL                    (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_UZ_LOW_AL                   ) // 1247
#define LUCHTMENGKAST_AFBLAASVENT_MB_N_LOW_AL                     (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_N_LOW_AL                    ) // 1248
#define LUCHTMENGKAST_AFBLAASVENT_MB_IGBT_FAULT_AL                (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_IGBT_FAULT_AL               ) // 1249
#define LUCHTMENGKAST_AFBLAASVENT_MB_UZK_HI_AL                    (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_UZK_HI_AL                   ) // 1250
#define LUCHTMENGKAST_AFBLAASVENT_MB_UZK_LO_AL                    (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_UZK_LO_AL                   ) // 1251
#define LUCHTMENGKAST_AFBLAASVENT_MB_UIN_HI_AL                    (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_UIN_HI_AL                   ) // 1252
#define LUCHTMENGKAST_AFBLAASVENT_MB_UIN_LO_AL                    (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_UIN_LO_AL                   ) // 1253
#define LUCHTMENGKAST_AFBLAASVENT_MB_FAILURE_POWER_SECTION_AL     (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_FAILURE_POWER_SECTION_AL    ) // 1254
#define LUCHTMENGKAST_AFBLAASVENT_MB_UMAX_AL                      (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_UMAX_AL                     ) // 1255
#define LUCHTMENGKAST_AFBLAASVENT_MB_UMIN_AL                      (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_UMIN_AL                     ) // 1256
#define LUCHTMENGKAST_AFBLAASVENT_MB_OVERSPEED_AL                 (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_OVERSPEED_AL                ) // 1257
#define LUCHTMENGKAST_AFBLAASVENT_MB_LOCKED_ROTOR_AL              (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_LOCKED_ROTOR_AL             ) // 1258
#define LUCHTMENGKAST_AFBLAASVENT_MB_UNDERSPEED_AL                (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_UNDERSPEED_AL               ) // 1259
#define LUCHTMENGKAST_AFBLAASVENT_MB_24V_SUPPLY_OVERLOADED_AL     (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_24V_SUPPLY_OVERLOADED_AL    ) // 1160
#define LUCHTMENGKAST_AFBLAASVENT_MB_INPUT_PHASE_ERROR_AL         (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_INPUT_PHASE_ERROR_AL        ) // 1061
#define LUCHTMENGKAST_AFBLAASVENT_MB_MOTOR_PHASE_ERROR_AL         (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_MOTOR_PHASE_ERROR_AL        ) // 1062
#define LUCHTMENGKAST_AFBLAASVENT_MB_MEMORY_ERROR_AL              (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_MEMORY_ERROR_AL             ) // 1063
#define LUCHTMENGKAST_AFBLAASVENT_MB_SHORT_CIRCUIT_AL             (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_SHORT_CIRCUIT_AL            ) // 1064
#define LUCHTMENGKAST_AFBLAASVENT_MB_LOSS_OF_SYNCHRONISM_AL       (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_LOSS_OF_SYNCHRONISM_AL      ) // 1065
#define LUCHTMENGKAST_AFBLAASVENT_MB_INPUT_VOLTAGE_ERROR_AL       (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_INPUT_VOLTAGE_ERROR_AL      ) // 1066
#define LUCHTMENGKAST_AFBLAASVENT_MB_INPUT_RELAY_NOT_CLOSED_AL    (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_INPUT_RELAY_NOT_CLOSED_AL   ) // 1067
#define LUCHTMENGKAST_AFBLAASVENT_MB_HIGH_STARTING_CURRENT_AL     (LUCHTMENGKAST_AFBLAASVENT_MB_AL + MB_DEVICE_HIGH_STARTING_CURRENT_AL    ) // 1068

#define KLEP_MB_AL                       1300
#define KLEP_MB_UNKNOWN_AL               (KLEP_MB_AL + MB_DEVICE_UNKNOWN_AL      ) // 1300
#define KLEP_MB_COMMUNICATION_AL         (KLEP_MB_AL + MB_DEVICE_COMMUNICATION_AL) // 1301

#define DRUKVERSCHIL_MB_AL               1400
#define DRUKVERSCHIL_MB_UNKNOWN_AL       (DRUKVERSCHIL_MB_AL + MB_DEVICE_UNKNOWN_AL      ) // 1400
#define DRUKVERSCHIL_MB_COMMUNICATION_AL (DRUKVERSCHIL_MB_AL + MB_DEVICE_COMMUNICATION_AL) // 1401

#define ONBEKEND_AL 0x7FFF

//==============================================================================
//------------------------ Alarm - Typedefs ------------------------------------
//==============================================================================
typedef struct
{
  int Code;
  int Priority;
  unsigned char mask; // MASK_AL_HARD MASK_AL_ZACHT MASK_AL_ONDERDRUKT
  void *Lcd;
  unsigned char pc_type; 
} TAlarm;

extern bit alarm_switch;
extern s_alarm_disp alarm_disp_act;
extern s_alarm_disp alarm_disp_pc;
#ifdef ALARM_TEKST_NAAR_SMARTLINK
extern unsigned int alarm_tekstread_mask;
extern int alarm_hard_actief_aantal; // JP 25-03-10
#endif // def ALARM_TEKST_NAAR_SMARTLINK

extern unsigned char alarm_disp_ico;
extern unsigned char alarm_blink_ico;
extern unsigned char alarm_disp_blocked;

extern unsigned char const zacht_alarm;
extern unsigned char const hard_alarm;

#define ZACHT_ALARM ((unsigned char *)&zacht_alarm)
#define HARD_ALARM  ((unsigned char *)&hard_alarm)

unsigned char CreateAlarm(unsigned char *al, int al_code, int al_index, int al_value, int al_group, unsigned char *al_hard);
unsigned char ClearAlarm(unsigned char *al, int al_code, int al_index);
void CreateAlarmValueChanged(unsigned char *al, int al_code, int al_index, int al_value, int al_group, unsigned char *al_hard);
void ChangeAlarmGroupBoardIO(s_board_IO_on_off *IO, int al_group);
void GetAlarm(int al_code, TAlarm *Alarm);

time_t TimeAlarmOn(int al_code, int al_index);
unsigned char AlarmHardGroup(int al_group);
unsigned char AlarmActiveGroup(int al_group, int al_code);

void Alarm_Control_Data_Algemeen(void);
void Alarm_Log_Opstart_Algemeen(void);
void Alarm_Reset_Data_PC_Algemeen(void);
void Alarm_Reset_Data_Algemeen(void);

unsigned char Alarm_Reset(s_alarm_disp *al);
void Alarm_Return(void);
void Alarm_Proc(void);

#endif
