#ifndef CONFIG_SERVICES_H
#define CONFIG_SERVICES_H

#define SERVICE_WHO_HAS
#define SERVICE_READ_PROPERTY
//#define SERVICE_READ_PROPERTY_MULTIPLE
#define SERVICE_WRITE_PROPERTY
#define SERVICE_COV
//#define BACFILE //Voor AtomicReadFile en AtomicWriteFile 
//#define SERVICE_REINITIALIZE_DEVICE
//#define SERVICE_DEVICE_COMMUNICATION_CONTROL
//#define SERVICE_TIME_SYNCHRONIZATION
//#define SERVICE_LIFE_SAFETY_OPERATION
//#define SERVICE_ALARM_ACK
//#define SERVICE_PRIVATE_TRANSFER
//#define SERVICE_READ_RANGE
//#define SERVICE_GET_EVENT_INFORMATION

#endif /* CONFIG_SERVICES_H */