/*
 * objects.h - generated object dictionary for a CANopen device
 *
 * Copyright 1998-2004 by port GmbH Halle(Saale) / Germany
 *-----------------------------------------------------------------------------
 *
 *-----------------------------------------------------------------------------
 *
 *
 * modification history
 * --------------------
 * $Log$
 * Revision 1.0  2011-07-18 11:49:04+02  driet
 * Initial revision
 *
 * Revision 1.10  2008-10-24 16:44:14+02  driet
 * <>
 *
 * Revision 1.9  2008-09-22 15:21:54+02  driet
 * <>
 *
 *
 *-----------------------------------------------------------------------------
 */ 

/**
* \file objects.h
* \author port GmbH, Halle (Saale)
*  $Revision$
*  $Date$
*
* This file contains the user selected objects for a CANopen device.
* It was generated by the CANopen Design Tool V 2.1.13 by port GmbH, Halle.
* Generation: 09-22-2008 12:02 PM
*
*/ 


/*  additional typedefs to those in headerfiles*/
#ifdef DEF_OBJ_DIC
/*  number of entries in the object dictionary */
UNSIGNED16	maxObjDicElements = 59;

/*  Definition of Variables (Device Objects)  */
UNSIGNED32		p301_DeviceType = { 0x000F0191UL };
UNSIGNED8		p301_ErrorRegister = { 0x00 };
UNSIGNED32		p301_PreDefinedErrorField[49] = { 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL};
UNSIGNED32		p301_CobIdSync = { 0x80000080UL };
UNSIGNED32		p301_SyncWindowLength = { 0x00000000UL };
VIS_STRING_T		p301_ManuDeviceName[8] = { "Hotraco" };
VIS_STRING_T		p301_ManuHardwareVersion[6] = { "0/0/0" };
VIS_STRING_T		p301_ManuSoftwareVersion[5] = { "2.00" };
UNSIGNED32		p301_CobIdEmcy = { 0x00000080UL };
UNSIGNED16		p301_InhibitEmcy = { 0x0 };
UNSIGNED32		p301_HbConsumer[2] = { 0x01UL, 0x00000000UL};
UNSIGNED16		p301_ProdHbTime = { 0x00000000 };
IDENTITY_T		p301_Identity = { 0x4, 0x0UL, 0x0UL, 0x0UL, 0x0UL };
PDO_COMM_PAR5_T		p301_n1_rpdo_para = { 0x05, 0x00000200UL, 0xFF, 0x0, 0x0, 0x0 };
PDO_COMM_PAR5_T		p301_n2_rpdo_para = { 0x05, 0x00000300UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n3_rpdo_para = { 0x05, 0x00000400UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n4_rpdo_para = { 0x05, 0x00000500UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n5_rpdo_para = { 0x05, 0x00000500UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n6_rpdo_para = { 0x05, 0x00000500UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n7_rpdo_para = { 0x05, 0x00000500UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n8_rpdo_para = { 0x05, 0x00000500UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n9_rpdo_para = { 0x05, 0x00000500UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_MAPPING8_T		p301_n1_rpdo_map = { 0x08, { 0x62000108UL, 0x62000208UL, 0x62000308UL, 0x62000408UL, 0x62000508UL, 0x62000608UL, 0x62000708UL, 0x62000808UL }};
PDO_MAPPING4_T		p301_n2_rpdo_map = { 0x04, { 0x64110110UL, 0x64110210UL, 0x64110310UL, 0x64110410UL }};
PDO_MAPPING4_T		p301_n3_rpdo_map = { 0x04, { 0x64110510UL, 0x64110610UL, 0x64110710UL, 0x64110810UL }};
PDO_MAPPING4_T		p301_n4_rpdo_map = { 0x04, { 0x64110910UL, 0x64110A10UL, 0x64110B10UL, 0x64110C10UL }};
PDO_MAPPING4_T		p301_n5_rpdo_map = { 0x04, { 0x64110D10UL, 0x64110E10UL, 0x64110F10UL, 0x64111010UL }};
PDO_MAPPING4_T		p301_n6_rpdo_map = { 0x04, { 0x64111110UL, 0x64111210UL, 0x64111310UL, 0x64111410UL }};
PDO_MAPPING4_T		p301_n7_rpdo_map = { 0x04, { 0x64111510UL, 0x64111610UL, 0x64111710UL, 0x64111810UL }};
PDO_MAPPING4_T		p301_n8_rpdo_map = { 0x04, { 0x64111910UL, 0x64111A10UL, 0x64111B10UL, 0x64111C10UL }};
PDO_MAPPING4_T		p301_n9_rpdo_map = { 0x04, { 0x64111D10UL, 0x64111E10UL, 0x64111F10UL, 0x64112010UL }};
PDO_COMM_PAR5_T		p301_n1_tpdo_para = { 0x05, 0x00000180UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n2_tpdo_para = { 0x05, 0x00000280UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n3_tpdo_para = { 0x05, 0x00000380UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n4_tpdo_para = { 0x05, 0x00000480UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n5_tpdo_para = { 0x05, 0x00000480UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n6_tpdo_para = { 0x05, 0x00000480UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n7_tpdo_para = { 0x05, 0x00000480UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n8_tpdo_para = { 0x05, 0x00000480UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n9_tpdo_para = { 0x05, 0x00000480UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n10_tpdo_para = { 0x05, 0x00000480UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_COMM_PAR5_T		p301_n11_tpdo_para = { 0x05, 0x00000480UL, 0xFF, 0x0, 0x00, 0x0 };
PDO_MAPPING8_T		p301_n1_tpdo_map = { 0x08, { 0x60000108UL, 0x60000208UL, 0x60000308UL, 0x60000408UL, 0x60000508UL, 0x60000608UL, 0x60000708UL, 0x60000808UL }};
PDO_MAPPING8_T		p301_n2_tpdo_map = { 0x08, { 0x60000908UL, 0x60000A08UL, 0x60000B08UL, 0x60000C08UL, 0x60000D08UL, 0x60000E08UL, 0x60000F08UL, 0x60001008UL }};
PDO_MAPPING4_T		p301_n3_tpdo_map = { 0x04, { 0x60001108UL, 0x60001208UL, 0x60001308UL, 0x60001408UL }};
PDO_MAPPING4_T		p301_n4_tpdo_map = { 0x04, { 0x64010110UL, 0x64010210UL, 0x64010310UL, 0x64010410UL }};
PDO_MAPPING4_T		p301_n5_tpdo_map = { 0x04, { 0x64010510UL, 0x64010610UL, 0x64010710UL, 0x64010810UL }};
PDO_MAPPING4_T		p301_n6_tpdo_map = { 0x04, { 0x64010910UL, 0x64010A10UL, 0x64010B10UL, 0x64010C10UL }};
PDO_MAPPING4_T		p301_n7_tpdo_map = { 0x04, { 0x64010D10UL, 0x64010E10UL, 0x64010F10UL, 0x64011010UL }};
PDO_MAPPING4_T		p301_n8_tpdo_map = { 0x04, { 0x60001108UL, 0x60001208UL, 0x60001308UL, 0x60001408UL }};
PDO_MAPPING4_T		p301_n9_tpdo_map = { 0x04, { 0x64011510UL, 0x64011610UL, 0x64011710UL, 0x64011810UL }};
PDO_MAPPING4_T		p301_n10_tpdo_map = { 0x04, { 0x64011910UL, 0x64011A10UL, 0x64011B10UL, 0x64011C10UL }};
PDO_MAPPING4_T		p301_n11_tpdo_map = { 0x04, { 0x64011D10UL, 0x64011E10UL, 0x64011F10UL, 0x64012010UL }};
UNSIGNED8		p401_ReadState8[21] = { 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
UNSIGNED8		p401_WriteState8[9] = { 0x8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
INTEGER16		p401_ReadAnin16[33] = { 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
INTEGER16		p401_WriteAnout16[33] = { 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
BOOL_T		p401_AninIntEnable = { 0 };
UNSIGNED32		p401_AninIntDelta[33] = { 0x20UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL};



/*  Definition of Value Descriptions  */
VALUE_DESC_T	CO_CONST	p301_DeviceType_desc[1] =  {
		    { 0x000F0191UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 }
		};
VALUE_DESC_T	CO_CONST	p301_ErrorRegister_desc[1] =  {
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 }
		};
VALUE_DESC_T	CO_CONST	p301_PreDefinedErrorField_desc[49] = {
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0x000000FEUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 }
		};
VALUE_DESC_T	CO_CONST	p301_CobIdSync_desc[1] =  {
		    { 0x80000080UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_SyncWindowLength_desc[1] =  {
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_ManuDeviceName_desc[1] =  {
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0x0UL,
#endif /* CONFIG_LIMITS_CHECK */
		    8, 0x20 }
		};
VALUE_DESC_T	CO_CONST	p301_ManuHardwareVersion_desc[1] =  {
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0x0UL,
#endif /* CONFIG_LIMITS_CHECK */
		    6, 0x20 }
		};
VALUE_DESC_T	CO_CONST	p301_ManuSoftwareVersion_desc[1] =  {
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0x0UL,
#endif /* CONFIG_LIMITS_CHECK */
		    5, 0x20 }
		};
VALUE_DESC_T	CO_CONST	p301_CobIdEmcy_desc[1] =  {
		    { 0x00000080UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 }
		};
VALUE_DESC_T	CO_CONST	p301_InhibitEmcy_desc[1] =  {
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_HbConsumer_desc[2] = {
		    { 0x01UL,
#ifdef CONFIG_LIMITS_CHECK
			0x1UL, 0x7FUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0x02FFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_ProdHbTime_desc[1] =  {
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_Identity_desc[5] = {
		    { 0x4UL,
#ifdef CONFIG_LIMITS_CHECK
			0x1UL, 0x4UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 }
		};
VALUE_DESC_T	CO_CONST	p301_n1_rpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000200UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0x07UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n2_rpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000300UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n3_rpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000400UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0x07UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n4_rpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000500UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0x07UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n5_rpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000500UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0x07UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n6_rpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000500UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0x07UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n7_rpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000500UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0x07UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n8_rpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000500UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0x07UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n9_rpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000500UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0x07UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n1_rpdo_map_desc[9] = {
		    { 0x08UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0x40UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x62000108UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x62000208UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x62000308UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x62000408UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x62000508UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x62000608UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x62000708UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x62000808UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n2_rpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64110110UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64110210UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64110310UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64110410UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n3_rpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64110510UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64110610UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64110710UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64110810UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n4_rpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64110910UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64110A10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64110B10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64110C10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n5_rpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64110D10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64110E10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64110F10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64111010UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n6_rpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64111110UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64111210UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64111310UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64111410UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n7_rpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64111510UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64111610UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64111710UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64111810UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n8_rpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64111910UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64111A10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64111B10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64111C10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n9_rpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64111D10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64111E10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64111F10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64112010UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n1_tpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000180UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n2_tpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000280UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n3_tpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000380UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n4_tpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000480UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n5_tpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000480UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n6_tpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000480UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n7_tpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000480UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n8_tpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000480UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n9_tpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000480UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n10_tpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000480UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n11_tpdo_para_desc[6] = {
		    { 0x05UL,
#ifdef CONFIG_LIMITS_CHECK
			0x02UL, 0x05UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00000480UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000001UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0xFFUL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0000UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    2, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n1_tpdo_map_desc[9] = {
		    { 0x08UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x60000108UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000208UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000308UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000408UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000508UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000608UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000708UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000808UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n2_tpdo_map_desc[9] = {
		    { 0x08UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x60000908UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000A08UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000B08UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000C08UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000D08UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000E08UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60000F08UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60001008UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n3_tpdo_map_desc[5] = {
		    { 0x4UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x60001108UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60001208UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60001308UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60001408UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n4_tpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64010110UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64010210UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64010310UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64010410UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n5_tpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64010510UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64010610UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64010710UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64010810UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n6_tpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64010910UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64010A10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64010B10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64010C10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n7_tpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64010D10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64010E10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64010F10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64011010UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n8_tpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x60001108UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60001208UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60001308UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x60001408UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n9_tpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64011510UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64011610UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64011710UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64011810UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n10_tpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64011910UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64011A10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64011B10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64011C10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p301_n11_tpdo_map_desc[5] = {
		    { 0x04UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 },
		    { 0x64011D10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64011E10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64011F10UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x64012010UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p401_ReadState8_desc[21] = {
		    { 0x14UL,
#ifdef CONFIG_LIMITS_CHECK
			0x01UL, 0xFEUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xB0 }
		};
VALUE_DESC_T	CO_CONST	p401_WriteState8_desc[9] = {
		    { 0x8UL,
#ifdef CONFIG_LIMITS_CHECK
			0x01UL, 0xFEUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x30 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xF0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xF0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xF0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xF0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xF0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xF0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xF0 },
		    { 0x00UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00UL, 0xFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0xF0 }
		};
VALUE_DESC_T	CO_CONST	p401_ReadAnin16_desc[33] = {
		    { 0x20UL,
#ifdef CONFIG_LIMITS_CHECK
			0x01UL, 0xFEUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0x30 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xB0 }
		};
VALUE_DESC_T	CO_CONST	p401_WriteAnout16_desc[33] = {
		    { 0x20UL,
#ifdef CONFIG_LIMITS_CHECK
			0x01UL, 0xFEUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0x30 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 },
		    { 0x0000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x8000UL, 0x7FFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    -2, 0xF0 }
		};
VALUE_DESC_T	CO_CONST	p401_AninIntEnable_desc[1] =  {
		    { 0UL,
#ifdef CONFIG_LIMITS_CHECK
			0x0UL, 0x1UL,
#endif /* CONFIG_LIMITS_CHECK */
		    1, 0x70 }
		};
VALUE_DESC_T	CO_CONST	p401_AninIntDelta_desc[33] = {
		    { 0x20UL,
#ifdef CONFIG_LIMITS_CHECK
			0x01UL, 0xFEUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x30 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 },
		    { 0x00000000UL,
#ifdef CONFIG_LIMITS_CHECK
			0x00000000UL, 0xFFFFFFFFUL,
#endif /* CONFIG_LIMITS_CHECK */
		    4, 0x70 }
		};
/* Definition of the object directory */

OBJDIR_T objDir[] = {
{   (UNSIGNED8 *)&p301_DeviceType,
    (VALUE_DESC_T *)p301_DeviceType_desc,
    0x1000, 1 }
   ,
{   (UNSIGNED8 *)&p301_ErrorRegister,
    (VALUE_DESC_T *)p301_ErrorRegister_desc,
    0x1001, 1 }
   ,
{   (UNSIGNED8 *)p301_PreDefinedErrorField,
    (VALUE_DESC_T *)p301_PreDefinedErrorField_desc,
    0x1003, 49 }
   ,
{   (UNSIGNED8 *)&p301_CobIdSync,
    (VALUE_DESC_T *)p301_CobIdSync_desc,
    0x1005, 1 }
   ,
{   (UNSIGNED8 *)&p301_SyncWindowLength,
    (VALUE_DESC_T *)p301_SyncWindowLength_desc,
    0x1007, 1 }
   ,
{   (UNSIGNED8 *)p301_ManuDeviceName,
    (VALUE_DESC_T *)p301_ManuDeviceName_desc,
    0x1008, 1 }
   ,
{   (UNSIGNED8 *)p301_ManuHardwareVersion,
    (VALUE_DESC_T *)p301_ManuHardwareVersion_desc,
    0x1009, 1 }
   ,
{   (UNSIGNED8 *)p301_ManuSoftwareVersion,
    (VALUE_DESC_T *)p301_ManuSoftwareVersion_desc,
    0x100A, 1 }
   ,
{   (UNSIGNED8 *)&p301_CobIdEmcy,
    (VALUE_DESC_T *)p301_CobIdEmcy_desc,
    0x1014, 1 }
   ,
{   (UNSIGNED8 *)&p301_InhibitEmcy,
    (VALUE_DESC_T *)p301_InhibitEmcy_desc,
    0x1015, 1 }
   ,
{   (UNSIGNED8 *)p301_HbConsumer,
    (VALUE_DESC_T *)p301_HbConsumer_desc,
    0x1016, 2 }
   ,
{   (UNSIGNED8 *)&p301_ProdHbTime,
    (VALUE_DESC_T *)p301_ProdHbTime_desc,
    0x1017, 1 }
   ,
{   (UNSIGNED8 *)&p301_Identity,
    (VALUE_DESC_T *)p301_Identity_desc,
    0x1018, 5 }
   ,
{   (UNSIGNED8 *)&p301_n1_rpdo_para,
    (VALUE_DESC_T *)p301_n1_rpdo_para_desc,
    0x1400, 6 }
   ,
{   (UNSIGNED8 *)&p301_n2_rpdo_para,
    (VALUE_DESC_T *)p301_n2_rpdo_para_desc,
    0x1401, 6 }
   ,
{   (UNSIGNED8 *)&p301_n3_rpdo_para,
    (VALUE_DESC_T *)p301_n3_rpdo_para_desc,
    0x1402, 6 }
   ,
{   (UNSIGNED8 *)&p301_n4_rpdo_para,
    (VALUE_DESC_T *)p301_n4_rpdo_para_desc,
    0x1403, 6 }
   ,
{   (UNSIGNED8 *)&p301_n5_rpdo_para,
    (VALUE_DESC_T *)p301_n5_rpdo_para_desc,
    0x1404, 6 }
   ,
{   (UNSIGNED8 *)&p301_n6_rpdo_para,
    (VALUE_DESC_T *)p301_n6_rpdo_para_desc,
    0x1405, 6 }
   ,
{   (UNSIGNED8 *)&p301_n7_rpdo_para,
    (VALUE_DESC_T *)p301_n7_rpdo_para_desc,
    0x1406, 6 }
   ,
{   (UNSIGNED8 *)&p301_n8_rpdo_para,
    (VALUE_DESC_T *)p301_n8_rpdo_para_desc,
    0x1407, 6 }
   ,
{   (UNSIGNED8 *)&p301_n9_rpdo_para,
    (VALUE_DESC_T *)p301_n9_rpdo_para_desc,
    0x1408, 6 }
   ,
{   (UNSIGNED8 *)&p301_n1_rpdo_map,
    (VALUE_DESC_T *)p301_n1_rpdo_map_desc,
    0x1600, 9 }
   ,
{   (UNSIGNED8 *)&p301_n2_rpdo_map,
    (VALUE_DESC_T *)p301_n2_rpdo_map_desc,
    0x1601, 5 }
   ,
{   (UNSIGNED8 *)&p301_n3_rpdo_map,
    (VALUE_DESC_T *)p301_n3_rpdo_map_desc,
    0x1602, 5 }
   ,
{   (UNSIGNED8 *)&p301_n4_rpdo_map,
    (VALUE_DESC_T *)p301_n4_rpdo_map_desc,
    0x1603, 5 }
   ,
{   (UNSIGNED8 *)&p301_n5_rpdo_map,
    (VALUE_DESC_T *)p301_n5_rpdo_map_desc,
    0x1604, 5 }
   ,
{   (UNSIGNED8 *)&p301_n6_rpdo_map,
    (VALUE_DESC_T *)p301_n6_rpdo_map_desc,
    0x1605, 5 }
   ,
{   (UNSIGNED8 *)&p301_n7_rpdo_map,
    (VALUE_DESC_T *)p301_n7_rpdo_map_desc,
    0x1606, 5 }
   ,
{   (UNSIGNED8 *)&p301_n8_rpdo_map,
    (VALUE_DESC_T *)p301_n8_rpdo_map_desc,
    0x1607, 5 }
   ,
{   (UNSIGNED8 *)&p301_n9_rpdo_map,
    (VALUE_DESC_T *)p301_n9_rpdo_map_desc,
    0x1608, 5 }
   ,
{   (UNSIGNED8 *)&p301_n1_tpdo_para,
    (VALUE_DESC_T *)p301_n1_tpdo_para_desc,
    0x1800, 6 }
   ,
{   (UNSIGNED8 *)&p301_n2_tpdo_para,
    (VALUE_DESC_T *)p301_n2_tpdo_para_desc,
    0x1801, 6 }
   ,
{   (UNSIGNED8 *)&p301_n3_tpdo_para,
    (VALUE_DESC_T *)p301_n3_tpdo_para_desc,
    0x1802, 6 }
   ,
{   (UNSIGNED8 *)&p301_n4_tpdo_para,
    (VALUE_DESC_T *)p301_n4_tpdo_para_desc,
    0x1803, 6 }
   ,
{   (UNSIGNED8 *)&p301_n5_tpdo_para,
    (VALUE_DESC_T *)p301_n5_tpdo_para_desc,
    0x1804, 6 }
   ,
{   (UNSIGNED8 *)&p301_n6_tpdo_para,
    (VALUE_DESC_T *)p301_n6_tpdo_para_desc,
    0x1805, 6 }
   ,
{   (UNSIGNED8 *)&p301_n7_tpdo_para,
    (VALUE_DESC_T *)p301_n7_tpdo_para_desc,
    0x1806, 6 }
   ,
{   (UNSIGNED8 *)&p301_n8_tpdo_para,
    (VALUE_DESC_T *)p301_n8_tpdo_para_desc,
    0x1807, 6 }
   ,
{   (UNSIGNED8 *)&p301_n9_tpdo_para,
    (VALUE_DESC_T *)p301_n9_tpdo_para_desc,
    0x1808, 6 }
   ,
{   (UNSIGNED8 *)&p301_n10_tpdo_para,
    (VALUE_DESC_T *)p301_n10_tpdo_para_desc,
    0x1809, 6 }
   ,
{   (UNSIGNED8 *)&p301_n11_tpdo_para,
    (VALUE_DESC_T *)p301_n11_tpdo_para_desc,
    0x180A, 6 }
   ,
{   (UNSIGNED8 *)&p301_n1_tpdo_map,
    (VALUE_DESC_T *)p301_n1_tpdo_map_desc,
    0x1A00, 9 }
   ,
{   (UNSIGNED8 *)&p301_n2_tpdo_map,
    (VALUE_DESC_T *)p301_n2_tpdo_map_desc,
    0x1A01, 9 }
   ,
{   (UNSIGNED8 *)&p301_n3_tpdo_map,
    (VALUE_DESC_T *)p301_n3_tpdo_map_desc,
    0x1A02, 5 }
   ,
{   (UNSIGNED8 *)&p301_n4_tpdo_map,
    (VALUE_DESC_T *)p301_n4_tpdo_map_desc,
    0x1A03, 5 }
   ,
{   (UNSIGNED8 *)&p301_n5_tpdo_map,
    (VALUE_DESC_T *)p301_n5_tpdo_map_desc,
    0x1A04, 5 }
   ,
{   (UNSIGNED8 *)&p301_n6_tpdo_map,
    (VALUE_DESC_T *)p301_n6_tpdo_map_desc,
    0x1A05, 5 }
   ,
{   (UNSIGNED8 *)&p301_n7_tpdo_map,
    (VALUE_DESC_T *)p301_n7_tpdo_map_desc,
    0x1A06, 5 }
   ,
{   (UNSIGNED8 *)&p301_n8_tpdo_map,
    (VALUE_DESC_T *)p301_n8_tpdo_map_desc,
    0x1A07, 5 }
   ,
{   (UNSIGNED8 *)&p301_n9_tpdo_map,
    (VALUE_DESC_T *)p301_n9_tpdo_map_desc,
    0x1A08, 5 }
   ,
{   (UNSIGNED8 *)&p301_n10_tpdo_map,
    (VALUE_DESC_T *)p301_n10_tpdo_map_desc,
    0x1A09, 5 }
   ,
{   (UNSIGNED8 *)&p301_n11_tpdo_map,
    (VALUE_DESC_T *)p301_n11_tpdo_map_desc,
    0x1A0A, 5 }
   ,
{   (UNSIGNED8 *)p401_ReadState8,
    (VALUE_DESC_T *)p401_ReadState8_desc,
    0x6000, 21 }
   ,
{   (UNSIGNED8 *)p401_WriteState8,
    (VALUE_DESC_T *)p401_WriteState8_desc,
    0x6200, 9 }
   ,
{   (UNSIGNED8 *)p401_ReadAnin16,
    (VALUE_DESC_T *)p401_ReadAnin16_desc,
    0x6401, 33 }
   ,
{   (UNSIGNED8 *)p401_WriteAnout16,
    (VALUE_DESC_T *)p401_WriteAnout16_desc,
    0x6411, 33 }
   ,
{   (UNSIGNED8 *)&p401_AninIntEnable,
    (VALUE_DESC_T *)p401_AninIntEnable_desc,
    0x6423, 1 }
   ,
{   (UNSIGNED8 *)p401_AninIntDelta,
    (VALUE_DESC_T *)p401_AninIntDelta_desc,
    0x6426, 33 }

};
#undef DEF_OBJ_DIC
#else


/* Declaration of Variables (Maintenance) */

extern UNSIGNED16	 maxObjDicElements;

/* Declaration of Variables (Device Objects) */

extern UNSIGNED32	p301_DeviceType;
extern UNSIGNED8	p301_ErrorRegister;
extern UNSIGNED32	p301_PreDefinedErrorField[49];
extern UNSIGNED32	p301_CobIdSync;
extern UNSIGNED32	p301_SyncWindowLength;
extern VIS_STRING_T	p301_ManuDeviceName[8];
extern VIS_STRING_T	p301_ManuHardwareVersion[6];
extern VIS_STRING_T	p301_ManuSoftwareVersion[5];
extern UNSIGNED32	p301_CobIdEmcy;
extern UNSIGNED16	p301_InhibitEmcy;
extern UNSIGNED32	p301_HbConsumer[2];
extern UNSIGNED16	p301_ProdHbTime;
extern IDENTITY_T	p301_Identity;
extern PDO_COMM_PAR5_T	p301_n1_rpdo_para;
extern PDO_COMM_PAR5_T	p301_n2_rpdo_para;
extern PDO_COMM_PAR5_T	p301_n3_rpdo_para;
extern PDO_COMM_PAR5_T	p301_n4_rpdo_para;
extern PDO_COMM_PAR5_T	p301_n5_rpdo_para;
extern PDO_COMM_PAR5_T	p301_n6_rpdo_para;
extern PDO_COMM_PAR5_T	p301_n7_rpdo_para;
extern PDO_COMM_PAR5_T	p301_n8_rpdo_para;
extern PDO_COMM_PAR5_T	p301_n9_rpdo_para;
extern PDO_MAPPING8_T	p301_n1_rpdo_map;
extern PDO_MAPPING4_T	p301_n2_rpdo_map;
extern PDO_MAPPING4_T	p301_n3_rpdo_map;
extern PDO_MAPPING4_T	p301_n4_rpdo_map;
extern PDO_MAPPING4_T	p301_n5_rpdo_map;
extern PDO_MAPPING4_T	p301_n6_rpdo_map;
extern PDO_MAPPING4_T	p301_n7_rpdo_map;
extern PDO_MAPPING4_T	p301_n8_rpdo_map;
extern PDO_MAPPING4_T	p301_n9_rpdo_map;
extern PDO_COMM_PAR5_T	p301_n1_tpdo_para;
extern PDO_COMM_PAR5_T	p301_n2_tpdo_para;
extern PDO_COMM_PAR5_T	p301_n3_tpdo_para;
extern PDO_COMM_PAR5_T	p301_n4_tpdo_para;
extern PDO_COMM_PAR5_T	p301_n5_tpdo_para;
extern PDO_COMM_PAR5_T	p301_n6_tpdo_para;
extern PDO_COMM_PAR5_T	p301_n7_tpdo_para;
extern PDO_COMM_PAR5_T	p301_n8_tpdo_para;
extern PDO_COMM_PAR5_T	p301_n9_tpdo_para;
extern PDO_COMM_PAR5_T	p301_n10_tpdo_para;
extern PDO_COMM_PAR5_T	p301_n11_tpdo_para;
extern PDO_MAPPING8_T	p301_n1_tpdo_map;
extern PDO_MAPPING8_T	p301_n2_tpdo_map;
extern PDO_MAPPING4_T	p301_n3_tpdo_map;
extern PDO_MAPPING4_T	p301_n4_tpdo_map;
extern PDO_MAPPING4_T	p301_n5_tpdo_map;
extern PDO_MAPPING4_T	p301_n6_tpdo_map;
extern PDO_MAPPING4_T	p301_n7_tpdo_map;
extern PDO_MAPPING4_T	p301_n8_tpdo_map;
extern PDO_MAPPING4_T	p301_n9_tpdo_map;
extern PDO_MAPPING4_T	p301_n10_tpdo_map;
extern PDO_MAPPING4_T	p301_n11_tpdo_map;

extern UNSIGNED8	p401_ReadState8[21];
extern UNSIGNED8	p401_WriteState8[9];
extern INTEGER16	p401_ReadAnin16[33];
extern INTEGER16	p401_WriteAnout16[33];
extern BOOL_T	p401_AninIntEnable;
extern UNSIGNED32	p401_AninIntDelta[33];


/* Declaration of Value Descriptions */

extern VALUE_DESC_T	CO_CONST p301_DeviceType_desc[1];
extern VALUE_DESC_T	CO_CONST p301_ErrorRegister_desc[1];
extern VALUE_DESC_T	CO_CONST p301_PreDefinedErrorField_desc[49];
extern VALUE_DESC_T	CO_CONST p301_CobIdSync_desc[1];
extern VALUE_DESC_T	CO_CONST p301_SyncWindowLength_desc[1];
extern VALUE_DESC_T	CO_CONST p301_ManuDeviceName_desc[1];
extern VALUE_DESC_T	CO_CONST p301_ManuHardwareVersion_desc[1];
extern VALUE_DESC_T	CO_CONST p301_ManuSoftwareVersion_desc[1];
extern VALUE_DESC_T	CO_CONST p301_CobIdEmcy_desc[1];
extern VALUE_DESC_T	CO_CONST p301_InhibitEmcy_desc[1];
extern VALUE_DESC_T	CO_CONST p301_HbConsumer_desc[2];
extern VALUE_DESC_T	CO_CONST p301_ProdHbTime_desc[1];
extern VALUE_DESC_T	CO_CONST p301_Identity_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n1_rpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n2_rpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n3_rpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n4_rpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n5_rpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n6_rpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n7_rpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n8_rpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n9_rpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n1_rpdo_map_desc[9];
extern VALUE_DESC_T	CO_CONST p301_n2_rpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n3_rpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n4_rpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n5_rpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n6_rpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n7_rpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n8_rpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n9_rpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n1_tpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n2_tpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n3_tpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n4_tpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n5_tpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n6_tpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n7_tpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n8_tpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n9_tpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n10_tpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n11_tpdo_para_desc[6];
extern VALUE_DESC_T	CO_CONST p301_n1_tpdo_map_desc[9];
extern VALUE_DESC_T	CO_CONST p301_n2_tpdo_map_desc[9];
extern VALUE_DESC_T	CO_CONST p301_n3_tpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n4_tpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n5_tpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n6_tpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n7_tpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n8_tpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n9_tpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n10_tpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p301_n11_tpdo_map_desc[5];
extern VALUE_DESC_T	CO_CONST p401_ReadState8_desc[21];
extern VALUE_DESC_T	CO_CONST p401_WriteState8_desc[9];
extern VALUE_DESC_T	CO_CONST p401_ReadAnin16_desc[33];
extern VALUE_DESC_T	CO_CONST p401_WriteAnout16_desc[33];
extern VALUE_DESC_T	CO_CONST p401_AninIntEnable_desc[1];
extern VALUE_DESC_T	CO_CONST p401_AninIntDelta_desc[33];

/* Declaration of Object Dictionary*/

extern OBJDIR_T	objDir[];

#endif


/*----------------------------------------------------------------------------*/
